#Workflow name
name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  #Build job
  maven_build:
    name: Maven Build
    permissions:
      id-token: write
      contents: read
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Maven Build
      - name: Maven Build
        run: mvn clean install
      #GCP Authentication
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL_PROJECT_ID }}/locations/global/workloadIdentityPools/wd-webapp-fe-pool/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          project_id: '${{ secrets.GCP_PROJECT }}'
      #GCP Deployment
      - name: Deploy to Google Cloud
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          project_id: '${{ secrets.GCP_PROJECT }}'
